services:
  # Base de datos
  db:
    image: postgres:15-alpine
    container_name: db-postgres-alpine
    environment:
      POSTGRES_USER: usuario_reto
      POSTGRES_PASSWORD: password_reto
      POSTGRES_DB: juego_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always

  # Backend Spring Boot
  backend:
    build: .             # Busca el Dockerfile en la carpeta actual
    container_name: app-backend-alpine
    ports:
      - "8080:8080"
    environment:
      # Aquí usamos el nombre del servicio 'db' como host
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/juego_db
      SPRING_DATASOURCE_USERNAME: usuario_reto
      SPRING_DATASOURCE_PASSWORD: password_reto
      # Configuramos Hibernate para que actualice tablas automáticamente
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 512M   # Límite duro para proteger tu EC2